version: '3'
services:
    redis:
        image: redis:4-alpine
        environment:
          - REDIS_PASSWORD=passwordRedis
        command: redis-server --appendonly yes
        container_name: redisDocker
    php:
        build: "./php-codepostal/"
        image: "anthonymasset/php-codepostal:latest"
        volumes:
            - "./php-codepostal/www/:/var/www/html/"
        ports:
            - "8080:80"
        links:
            - redis:redisDocker
    db:
        build: "./mysql-codepostal/"
        image: "anthonymasset/mysql-codepostal:latest"
        ports:
            - "3307:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
